### ISSUE TITLE
Reduce public api surface 

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1989]
## description
Reduce and document the interface of available API in order to  (1) have more flexibility in refactoring, (2) simplify usage, and (3) increase dev-velocity  

### related issues
- some of the exports in `@stylable/core` are deprecated as part of (#1884 ) 

### tasks overview
- [x] remove export `*` from all packages
- [x] add deprecation tools to help mark exports / usages that are not intended to be maintained as public API
- [x] reduce exports only to what is actually intended to be public (will require direct imports in internal test specs)
- [x] document intended public API in packages README (and repository wiki where it seems logical) - https://github.com/wixplosives/stylable.io/issues/56
