### ISSUE TITLE
Add CLI codemods

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#1997]
### description
<what is this and why are we doing it>
Codemods is a new CLI feature that allow to transform Stylable AST and keep the same behavior when new features replaces old ones. 
This CLI will allow us to migrate old syntax quickly and with that deprecate features in a more "dev friendly" way.
Codemods will be exposed when installing `@stylable/cli` under the CLI bin `stc-codemod`

We are planning to introduce the following codemods:
- :import to @st-import
- :vars to @st-vars (future)
- animation-name to stGlobal(name) (when we start to emit errors)

### tags
<keywords that relate to this task>

### related issues
https://github.com/wix/stylable/pull/1693 This is the PR that implements codemods CLI

### blocked by (dependencies)
This is only blocked by the idea that we should somehow preserve comments/indentations from user source.

### blocks other
<description of other tasks that are blocked from completing by this task>

### tasks overview

- [x] resolve the comments/indentations concerns 
- [x] ability to report when something fishy can happen
- [x] document the safety net of using code mods (per code mod)
- [x] merge PR
