### ISSUE TITLE
@Stylable v0.1.0

### ISSUE THREAD

**Issue by tomrav** [wix/stylable#361]
### Infrastructure
- [x] Migrate to scoped mono-repo package
  - Move all Stylable related packages to a `@stylable` npm [scoped package](https://docs.npmjs.com/misc/scope)
  - Reset core versioning to `v0.1.0`
  - Publish new packages to scope
    - `build-test-kit`
    - `cli`
    - `jest`
    - `node`
    - `webpack-extensions`
    - `stylable.io`
- [x] Upgrade TypeScript version to `v2.9.2`
  - Refactor runtime types to a single location

### New / changed features
- [x] Decrease specificity for `-st-extends` (#355)
- [x] Make preparation warnings for upcoming native CSS variables feature (#247)
  - Warn about any `state` starting with `--` (reserved CSS syntax)

### Deprecations and clean ups

- [ ] Deprecate package
  - Add deprecation warning for all `stylable-*` packages (out of @stylable)
  - `stylable-integration` - webpack `v3.x` support
- [x] Remove deprecated features
  - `bundler`
  - `-st-theme`
  - `-st-compose` (#218)
- [x] Remove stale `root scoping` from code (#217)

### Documentation
- [x] Re-write main mono-repo `README` to reflect new structure and packages
- [x] Document README for all newly published packages
- [x] Remove deprecated playground from [stylable.io](https://stylable.io)

**Comment by idoros** [comment]
please don't depracate `-st-global`, lets document it as experimental and warn when used.
